version: "3.2"

services:
  nginx:
    image: gcr.io/micro-289001/github.com/jadoint/micro-nginx:frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./private/ssl:/etc/nginx/ssl
    environment:
      - NGINX_HOST=www.yoursite.com
    depends_on:
      - blog
      - user
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    command:
      - /bin/sh
      - -c
      - |
        envsubst '$${NGINX_HOST}'< /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
        exec nginx -g 'daemon off;'
  blog:
    image: gcr.io/micro-289001/github.com/jadoint/micro-blog:blog
    volumes:
      - ./private/ssl:/etc/nginx/ssl
      - ./private/ssl:/home/ssl
    environment:
      - ENV=production
      - LISTEN=:9000
      - SITE_URL=https://www.yoursite.com
      - START_PATH=api/v1
      - DB_NAME=blog
      - DB_USER=yourdbuser
      - DB_PASSWORD=yourdbpassword
      - DB_PROTOCOL=tcp
      - DB_MASTER_HOST=db-blog
      - DB_READ_HOST=db-blog
      - DB_PORT=3306
      - CACHE_ADDR=redis:6379
      - COOKIE_SESSION_NAME=and0
      - IS_SECURE_COOKIE=true
      - JWT_ALGO=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - JWT_KEY=abcdefghijklmnopqrstuvwxyz
      - TLS_CERT=/home/ssl/site.pem
      - TLS_KEY=/home/ssl/site.key
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  user:
    image: gcr.io/micro-289001/github.com/jadoint/micro-user:user
    volumes:
      - ./private/ssl:/etc/nginx/ssl
      - ./private/ssl:/home/ssl
    environment:
      - ENV=production
      - LISTEN=:9000
      - SITE_URL=https://wwww.yoursite.com
      - START_PATH=api/v1
      - DB_NAME=user
      - DB_USER=yourdbuser
      - DB_PASSWORD=yourdbpassword
      - DB_PROTOCOL=tcp
      - DB_MASTER_HOST=db-user
      - DB_READ_HOST=db-user
      - DB_PORT=3306
      - CACHE_ADDR=redis:6379
      - COOKIE_SESSION_NAME=and0
      - IS_SECURE_COOKIE=true
      - JWT_ALGO=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - JWT_KEY=abcdefghijklmnopqrstuvwxyz
      - TLS_CERT=/home/ssl/site.pem
      - TLS_KEY=/home/ssl/site.key
      - RECAPTCHA_KEY=abcdefghijklmnopqrstuvwxyz
      # Score threshold recommended default is 0.5.
      # Lower this value for stricter policies or
      # increase it for more leniency.
      - RECAPTCHA_SCORE_THRESHOLD=0.5
      # Restrict visitors from registering
      - SIGNUPS_RESTRICTED=false
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  db-user:
    image: gcr.io/micro-289001/github.com/jadoint/micro-db-user:db-user
    volumes:
      - ./mysql/micro-user/data:/var/lib/mysql
      - ./mysql/micro-user/backups:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=user
      - MYSQL_USER=yourdbuser
      - MYSQL_PASSWORD=yourdbpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  db-blog:
    image: gcr.io/micro-289001/github.com/jadoint/micro-db-blog:db-blog
    volumes:
      - ./mysql/micro-blog/data:/var/lib/mysql
      - ./mysql/micro-blog/backups:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlrootpassword
      - MYSQL_DATABASE=blog
      - MYSQL_USER=yourdbuser
      - MYSQL_PASSWORD=yourdbpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  redis:
    image: gcr.io/micro-289001/github.com/jadoint/micro-redis:redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
