version: "3"

services:
  blog:
    image: dockerhub_name/go-micro-blog
    build:
      context: ./cmd/blog
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"
    volumes:
      - ~/go/src/github.com/dockerhub_name/micro:/home/app
    environment:
      - ENV=development
      - LISTEN=:8001
      - SITE_URL=http://localhost:3000
      - START_PATH=api/v1
      - DB_NAME=blog
      - DB_USER=yourdbusername
      - DB_PASSWORD=yourdbpassword
      - DB_PROTOCOL=tcp
      - DB_MASTER_HOST=db-blog-dev
      - DB_READ_HOST=db-blog-dev
      - DB_PORT=3306
      - CACHE_ADDR=redis:6379
      - COOKIE_SESSION_NAME=and0
      - IS_SECURE_COOKIE=true
      - JWT_ALGO=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - JWT_KEY=abcdefghijklmnopqrstuvwxyz123456
      - TLS_CERT=/home/app/deployments/tls/localhost.pem
      - TLS_KEY=/home/app/deployments/tls/localhost.key
    restart: always
    depends_on:
      - db-blog-dev
      - redis
  user:
    image: dockerhub_name/go-micro-user
    build:
      context: ./cmd/user
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ~/go/src/github.com/dockerhub_name/micro:/home/app
    environment:
      - ENV=development
      - LISTEN=:8000
      - SITE_URL=http://localhost:3000
      - START_PATH=api/v1
      - DB_NAME=user
      - DB_USER=yourdbusername
      - DB_PASSWORD=yourdbpassword
      - DB_PROTOCOL=tcp
      - DB_MASTER_HOST=db-user-dev
      - DB_READ_HOST=db-user-dev
      - DB_PORT=3306
      - CACHE_ADDR=redis:6379
      - COOKIE_SESSION_NAME=and0
      - IS_SECURE_COOKIE=true
      - JWT_ALGO=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - JWT_KEY=abcdefghijklmnopqrstuvwxyz123456
      - TLS_CERT=/home/app/deployments/tls/localhost.pem
      - TLS_KEY=/home/app/deployments/tls/localhost.key
      - RECAPTCHA_KEY=abcdefghijklmnopqrstuvwxyz123456
      - RECAPTCHA_SCORE_THRESHOLD=0.5
      - SIGNUPS_RESTRICTED=true
    restart: always
    depends_on:
      - db-user-dev
      - redis
  db-user-dev:
    image: dockerhub_name/db-micro-user
    build:
      context: ./deployments/database/user
      dockerfile: Dockerfile.dev
    ports:
      - "3400:3306"
    volumes:
      - ~/mysql/micro-user/data:/var/lib/mysql
      - ~/mysql/micro-user/backups:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=yourdbrootpassword
      - MYSQL_DATABASE=user
      - MYSQL_USER=yourdbusername
      - MYSQL_PASSWORD=yourdbpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    restart: always
  db-blog-dev:
    image: dockerhub_name/db-micro-blog
    build:
      context: ./deployments/database/blog
      dockerfile: Dockerfile.dev
    ports:
      - "3401:3306"
    volumes:
      - ~/mysql/micro-blog/data:/var/lib/mysql
      - ~/mysql/micro-blog/backups:/backups
    environment:
      - MYSQL_ROOT_PASSWORD=yourdbrootpassword
      - MYSQL_DATABASE=blog
      - MYSQL_USER=yourdbusername
      - MYSQL_PASSWORD=yourdbpassword
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
    restart: always
  redis:
    image: dockerhub_name/redis
    build:
      context: ./deployments/cache
    ports:
      - "6379:6379"
    restart: always
