FROM golang:latest
LABEL Name=go-micro-user
WORKDIR /home/app
RUN go get github.com/githubnemo/CompileDaemon
ENTRYPOINT CompileDaemon --build="go build -o micro_user_service /home/app/cmd/user/main.go" --command="./micro_user_service" --exclude-dir=.git --exclude-dir=web --exclude-dir=deployments
EXPOSE 8000